spring.application.name=AUTH-SERVICE
server.port=${PORT:8080}

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
jwt.secretKey=${JWT_SECRET}

# Eureka
eureka.client.service-url.defaultZone=https://quantitymeasurementapp-production-d15a.up.railway.app/eureka
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=auth-service-production-bd6e.up.railway.app
eureka.instance.non-secure-port=443
eureka.instance.non-secure-port-enabled=true
eureka.instance.secure-port-enabled=false
eureka.instance.status-page-url=https://auth-service-production-bd6e.up.railway.app/actuator/info
eureka.instance.health-check-url=https://auth-service-production-bd6e.up.railway.app/actuator/health
eureka.instance.home-page-url=https://auth-service-production-bd6e.up.railway.app/

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.google.client-name=Google
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub

# Logging
logging.level.org.springframework.security=INFO

# Swagger/OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.server-url=https://api-gateway-production-d707.up.railway.app

# Actuator
management.endpoints.web.exposure.include=*