spring.application.name=AUTH-SERVICE
server.port=${PORT:8081}


spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/quantitymeasurementdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:physics123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false


jwt.secretKey=${JWT_SECRET:jdhwuydhwiedhud52e5dew5dfff63f43fwefw5ffwfwfbhwjf5wwadwdbjwbdww65wwdwebjdw}


spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri=${OAUTH_URI:http://localhost:8081/login/oauth2/code/google}
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.google.client-name=Google
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub


eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=${RAILWAY_PRIVATE_DOMAIN:localhost}
eureka.instance.non-secure-port=${PORT:8081}
eureka.instance.instance-id=${spring.application.name}:${PORT:8081}
eureka.instance.status-page-url=http://${RAILWAY_PRIVATE_DOMAIN:localhost}:${PORT:8081}/actuator/info
eureka.instance.health-check-url=http://${RAILWAY_PRIVATE_DOMAIN:localhost}:${PORT:8081}/actuator/health
eureka.instance.home-page-url=http://${RAILWAY_PRIVATE_DOMAIN:localhost}:${PORT:8081}/


springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true


logging.level.org.springframework.security=WARN
logging.level.root=INFO


management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always