spring.application.name=QUANTITY-SERVICE
server.port=${PORT:8082}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secretKey=jdhwuydhwiedhud52e5dew5dfff63f43fwefw5ffwfwfbhwjf5wwadwdbjwbdww65wwdwebjdw

# eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.service-url.defaultZone=https://quantitymeasurementapp-production-d15a.up.railway.app/eureka
eureka.instance.prefer-ip-address=true

springdoc.api-docs.path=/v3/api-docs
management.endpoints.web.exposure.include=*

springdoc.swagger-ui.server-url=springdoc.swagger-ui.server-url=https://api-gateway-production-d707.up.railway.app
# springdoc.api-docs.path=/v3/api-docs
# springdoc.swagger-ui.path=/swagger-ui.html
# springdoc.swagger-ui.server-url=http://localhost:8080
# springdoc.override-with-generic-response=false

