spring.application.name=QUANTITY-SERVICE
server.port=${PORT:8082}

# Database
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/quantitymeasurementdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:physics123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# JWT
jwt.secretKey=${JWT_SECRET:jdhwuydhwiedhud52e5dew5dfff63f43fwefw5ffwfwfbhwjf5wwadwdbjwbdww65wwdwebjdw}

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=${RAILWAY_PRIVATE_DOMAIN:localhost}
eureka.instance.non-secure-port=${PORT:8082}
eureka.instance.instance-id=${spring.application.name}:${PORT:8082}
eureka.instance.status-page-url=http://${RAILWAY_PRIVATE_DOMAIN:localhost}:${PORT:8082}/actuator/info
eureka.instance.health-check-url=http://${RAILWAY_PRIVATE_DOMAIN:localhost}:${PORT:8082}/actuator/health
eureka.instance.home-page-url=http://${RAILWAY_PRIVATE_DOMAIN:localhost}:${PORT:8082}/

# Springdoc
springdoc.api-docs.path=/v3/api-docs
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true

# Logging
logging.level.root=INFO


# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always