spring.application.name=QUANTITY-SERVICE
server.port=${PORT:8080}

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
jwt.secretKey=${JWT_SECRET}

# Eureka
eureka.client.service-url.defaultZone=https://quantitymeasurementapp-production-d15a.up.railway.app/eureka
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=quantity-service-production-f399.up.railway.app
eureka.instance.non-secure-port=443
eureka.instance.non-secure-port-enabled=true
eureka.instance.secure-port-enabled=false
eureka.instance.status-page-url=https://quantity-service-production-f399.up.railway.app/actuator/info
eureka.instance.health-check-url=https://quantity-service-production-f399.up.railway.app/actuator/health
eureka.instance.home-page-url=https://quantity-service-production-f399.up.railway.app/

# Swagger/OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.server-url=https://api-gateway-production-d707.up.railway.app

# Actuator
management.endpoints.web.exposure.include=*