spring.application.name=EUREKA-SERVER
server.port=${PORT:8761}

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
eureka.server.wait-time-in-ms-when-sync-empty=0

eureka.instance.hostname=${RAILWAY_PUBLIC_DOMAIN:localhost}
eureka.instance.prefer-ip-address=false

eureka.server.enable-self-preservation=false
eureka.server.eviction-interval-timer-in-ms=5000

logging.level.root=INFO
logging.level.com.netflix.eureka=INFO
logging.level.com.netflix.discovery=INFO