server.port=${PORT:8761}
server.address=0.0.0.0
server.forward-headers-strategy=framework

spring.application.name=EUREKA-SERVER

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# # Nice dashboard
# eureka.instance.hostname=localhost